apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Configuration
metadata:
  name: custom-config
spec:
  # namespace: chainsaw
  timeouts:
    apply: 120s
    assert: 220s
    cleanup: 120s
    delete: 120s
    error: 120s
    exec: 150s
  # skipDelete: true
  failFast: true
  parallel: 1
  forceTerminationGracePeriod: 10s
